name: Build Quake iOS

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build and Detect Scheme
        run: |
          # 1. Entra na pasta do projeto
          cd ios
          
          # 2. Descobre o nome do projeto e o Scheme real
          PROJ_FILE=$(ls -d *.xcodeproj | head -n 1)
          SCHEME_NAME=$(xcodebuild -list -project "$PROJ_FILE" | grep -A 1 "Schemes:" | tail -n 1 | xargs)
          
          echo "Projeto encontrado: $PROJ_FILE"
          echo "Scheme detectado: $SCHEME_NAME"

          # 3. Compila usando os nomes que ele mesmo descobriu
          xcodebuild archive \
            -project "$PROJ_FILE" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ./Quake.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            AD_HOC_CODE_SIGNING_ALLOWED=YES

      - name: Zip for Download
        if: always()
        run: |
          # Procura o arquivo xcarchive em qualquer lugar e zipa
          find . -name "*.xcarchive" -exec zip -r Quake_Ready.zip {} +

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Quake-iOS-Build
          path: "**/*.zip"
